#!/bin/bash
SELF=$(readlink -f "$0")
DIR="$(dirname "$SELF")"
# Prefer .se/venv python if available
if [ -f "$DIR/../.se/venv/Scripts/python.exe" ]; then
    exec "$DIR/../.se/venv/Scripts/python.exe" "$DIR/se.py" "$@"
else
    exec python "$DIR/se.py" "$@"
fi
